# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 335859299c91f2ffd356199f92c3f80954d36e58347d23cc6658a46c79fd764fdac0336c9928bcf205cd4578972ddda25308b867ba126bcf1b728574485cf86b

test:
  secret_key_base: f4a1eba8a1c2e909cbbe802af5276887563f575165863b6b9f4efda8c523ffa0ad74ec0af99be63937041100d849b0eca5d3cd75de5a06ab59474af00f9bfb9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
